{
 "title": "Environment",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "`C Bed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT\n\tCAST(json_extract(data, '$.t') AS FLOAT) as \"`C Front\"\nFROM telemetry\nORDER BY event_date DESC\nLIMIT 1",
     "rawQueryText": "SELECT\n\tCAST(json_extract(data, '$.t') AS FLOAT) as \"`C Front\"\nFROM telemetry\nORDER BY event_date DESC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "`C Rump",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT\n\tCAST(json_extract(data, '$.t') AS FLOAT) as \"`C Rump\"\nFROM telemetry\nORDER BY event_date DESC\nLIMIT 1",
     "rawQueryText": "SELECT\n\tCAST(json_extract(data, '$.t') AS FLOAT) as \"`C Rump\"\nFROM telemetry\nORDER BY event_date DESC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "`C Pod",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT\n\tCAST(json_extract(data, '$.t') AS FLOAT) as \"`C Pod\"\nFROM telemetry\nORDER BY event_date DESC\nLIMIT 1",
     "rawQueryText": "SELECT\n\tCAST(json_extract(data, '$.t') AS FLOAT) as \"`C Pod\"\nFROM telemetry\nORDER BY event_date DESC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "RH Rump",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT\n\tCAST(json_extract(data, '$.rh') AS FLOAT) as \"rh Rump\"\nFROM telemetry\nORDER BY event_date DESC\nLIMIT 1",
     "rawQueryText": "SELECT\n\tCAST(json_extract(data, '$.rh') AS FLOAT) as \"rh Rump\"\nFROM telemetry\nORDER BY event_date DESC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "RH Bed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT\n\tCAST(json_extract(data, '$.rh') AS FLOAT) as \"rh bed\"\nFROM telemetry\nORDER BY event_date DESC\nLIMIT 1",
     "rawQueryText": "SELECT\n\tCAST(json_extract(data, '$.rh') AS FLOAT) as \"rh bed\"\nFROM telemetry\nORDER BY event_date DESC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "hpa",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT\n\tCAST(json_extract(data, '$.hpa') AS FLOAT) as \"hpa\"\nFROM telemetry\nORDER BY event_date DESC\nLIMIT 1",
     "rawQueryText": "SELECT\n\tCAST(json_extract(data, '$.hpa') AS FLOAT) as \"hpa\"\nFROM telemetry\nORDER BY event_date DESC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "hpa Pod",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT\n\tCAST(json_extract(data, '$.hpa') AS FLOAT) as \"hpa Pod\"\nFROM telemetry\nORDER BY event_date DESC\nLIMIT 1",
     "rawQueryText": "SELECT\n\tCAST(json_extract(data, '$.hpa') AS FLOAT) as \"hpa Pod\"\nFROM telemetry\nORDER BY event_date DESC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "queryText": "SELECT \n\tevent_date, \n\tCAST(json_extract(data, '$.t') AS FLOAT) as \"`C Front\"\nFROM telemetry\nWHERE event_date BETWEEN 1738448040 AND 1738469640\nGROUP BY 1\nORDER BY 1 ASC",
     "rawQueryText": "SELECT \n\tevent_date, \n\tCAST(json_extract(data, '$.t') AS FLOAT) as \"`C Front\"\nFROM telemetry\nWHERE event_date BETWEEN ${__from:date:seconds} AND ${__to:date:seconds}\nGROUP BY 1\nORDER BY 1 ASC",
     "timeColumns": [ "event_date" ]
    },
    {
     "queryText": "SELECT \n\tevent_date, \n\tCAST(json_extract(data, '$.t') AS FLOAT) as \"`C rump\"\nFROM telemetry\nWHERE event_date BETWEEN ${__from:date:seconds} AND ${__to:date:seconds}\nGROUP BY 1\nORDER BY 1 ASC",
     "rawQueryText": "SELECT \n\tevent_date, \n\tCAST(json_extract(data, '$.t') AS FLOAT) as \"`C rump\"\nFROM telemetry\nWHERE event_date BETWEEN ${__from:date:seconds} AND ${__to:date:seconds}\nGROUP BY 1\nORDER BY 1 ASC",
     "timeColumns": [ "event_date" ]
    },
    {
     "queryText": "SELECT \n\tevent_date, \n\tCAST(json_extract(data, '$.t') AS FLOAT) as \"`C Pod\"\nFROM telemetry\nWHERE event_date BETWEEN 1738448040 AND 1738469640\nGROUP BY 1\nORDER BY 1 ASC",
     "rawQueryText": "SELECT \n\tevent_date, \n\tCAST(json_extract(data, '$.t') AS FLOAT) as \"`C Pod\"\nFROM telemetry\nWHERE event_date BETWEEN ${__from:date:seconds} AND ${__to:date:seconds}\nGROUP BY 1\nORDER BY 1 ASC",
     "timeColumns": [ "event_date" ]
    }
   ]
  },
  {
   "title": "Barometric Pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "queryText": "SELECT \n\tevent_date, \n\tCAST(json_extract(data, '$.hpa') AS FLOAT) as \"hpa\"\nFROM telemetry\nWHERE event_date BETWEEN ${__from:date:seconds} AND ${__to:date:seconds}\nGROUP BY 1\nORDER BY 1 ASC",
     "rawQueryText": "SELECT \n\tevent_date, \n\tCAST(json_extract(data, '$.hpa') AS FLOAT) as \"hpa\"\nFROM telemetry\nWHERE event_date BETWEEN ${__from:date:seconds} AND ${__to:date:seconds}\nGROUP BY 1\nORDER BY 1 ASC",
     "timeColumns": [ "event_date" ]
    },
    {
     "queryText": "SELECT \n\tevent_date, \n\tCAST(json_extract(data, '$.hpa') AS FLOAT) as \"hpa Pod\"\nFROM telemetry\nWHERE event_date BETWEEN ${__from:date:seconds} AND ${__to:date:seconds}\nGROUP BY 1\nORDER BY 1 ASC",
     "rawQueryText": "SELECT \n\tevent_date, \n\tCAST(json_extract(data, '$.hpa') AS FLOAT) as \"hpa Pod\"\nFROM telemetry\nWHERE event_date BETWEEN ${__from:date:seconds} AND ${__to:date:seconds}\nGROUP BY 1\nORDER BY 1 ASC",
     "timeColumns": [ "event_date" ]
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "queryText": "SELECT \n\tevent_date, \n\tCAST(json_extract(data, '$.rh') AS FLOAT) as \"rh bed\"\nFROM telemetry\nWHERE event_date BETWEEN ${__from:date:seconds} AND ${__to:date:seconds}\nGROUP BY 1\nORDER BY 1 ASC",
     "rawQueryText": "SELECT \n\tevent_date, \n\tCAST(json_extract(data, '$.rh') AS FLOAT) as \"rh bed\"\nFROM telemetry\nWHERE event_date BETWEEN ${__from:date:seconds} AND ${__to:date:seconds}\nGROUP BY 1\nORDER BY 1 ASC",
     "timeColumns": [ "event_date" ]
    },
    {
     "queryText": "SELECT \n\tevent_date, \n\tCAST(json_extract(data, '$.rh') AS FLOAT) as \"rh rump\"\nFROM telemetry\nWHERE event_date BETWEEN ${__from:date:seconds} AND ${__to:date:seconds}\nGROUP BY 1\nORDER BY 1 ASC",
     "rawQueryText": "SELECT \n\tevent_date, \n\tCAST(json_extract(data, '$.rh') AS FLOAT) as \"rh rump\"\nFROM telemetry\nWHERE event_date BETWEEN ${__from:date:seconds} AND ${__to:date:seconds}\nGROUP BY 1\nORDER BY 1 ASC",
     "timeColumns": [ "event_date" ]
    }
   ]
  },
  {
   "title": "Pod Air Quality",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "queryText": "SELECT \n\tevent_date, \n\tCAST(json_extract(data, '$.aq') AS FLOAT) as \"aq\"\nFROM telemetry\nWHERE event_date BETWEEN 1773512151 AND 1773533751\nGROUP BY 1\nORDER BY 1 ASC",
     "rawQueryText": "SELECT \n\tevent_date, \n\tCAST(json_extract(data, '$.aq') AS FLOAT) as \"aq\"\nFROM telemetry\nWHERE event_date BETWEEN ${__from:date:seconds} AND ${__to:date:seconds}\nGROUP BY 1\nORDER BY 1 ASC",
     "timeColumns": [ "event_date" ]
    },
    {
     "queryText": "SELECT \n\tevent_date, \n\tCAST(json_extract(data, '$.co2') AS FLOAT) as \"co2\"\nFROM telemetry\nWHERE event_date BETWEEN 1773512151 AND 1773533751\nGROUP BY 1\nORDER BY 1 ASC",
     "rawQueryText": "SELECT \n\tevent_date, \n\tCAST(json_extract(data, '$.co2') AS FLOAT) as \"co2\"\nFROM telemetry\nWHERE event_date BETWEEN ${__from:date:seconds} AND ${__to:date:seconds}\nGROUP BY 1\nORDER BY 1 ASC",
     "timeColumns": [ "event_date" ]
    },
    {
     "queryText": "SELECT \n\tevent_date, \n\tCAST(json_extract(data, '$.voc') AS FLOAT) as \"voc\"\nFROM telemetry\nWHERE event_date BETWEEN 1773512151 AND 1773533751\nGROUP BY 1\nORDER BY 1 ASC",
     "rawQueryText": "SELECT \n\tevent_date, \n\tCAST(json_extract(data, '$.voc') AS FLOAT) as \"voc\"\nFROM telemetry\nWHERE event_date BETWEEN ${__from:date:seconds} AND ${__to:date:seconds}\nGROUP BY 1\nORDER BY 1 ASC",
     "timeColumns": [ "event_date" ]
    }
   ]
  }
 ]
}