{
 "title": "Power Consumption",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Power Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  event_date AS \"time\",\n  (data->'ws')::float * 3600\nFROM power_usage\nORDER BY event_date desc\nlimit 1"
    }
   ]
  },
  {
   "title": "Cost ($)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(event_date,1h),\n  data_type AS metric,\n  ((avg((data->'ws')::float) * 3600) / 1000) * 0.2547 AS \"data\"\nFROM power_usage\nWHERE\n  $__timeFilter(event_date) AND\n  data_type = 'm1'\nGROUP BY 1,2\nORDER BY 1,2\n"
    }
   ]
  },
  {
   "title": "Usage W/s",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  event_date AS \"time\",\n  data_type AS metric,\n  (data->'ws')::float\nFROM power_usage\nWHERE\n  $__timeFilter(event_date) AND\n  data_type = 'm1'\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Power Usage (kWh)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(event_date,1h),\n  data_type AS metric,\n  avg((data->'ws')::float) * 3600 AS \"data\"\nFROM power_usage\nWHERE\n  $__timeFilter(event_date) AND\n  data_type = 'm1'\nGROUP BY 1,2\nORDER BY 1,2"
    }
   ]
  }
 ]
}