{
 "title": "Server Stats",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "queryText": "SELECT \n\t$__unixEpochGroupSeconds(event_date, 60, NULL) as event_date, \n\tavg(json_extract(data, '$.c')) as \"cpu\"\nFROM telemetry\nWHERE event_date BETWEEN ${__from:date:seconds} AND ${__to:date:seconds}\nGROUP BY 1\nORDER BY 1 ASC",
     "rawQueryText": "SELECT \n\t$__unixEpochGroupSeconds(event_date, 60, NULL) as event_date, \n\tavg(json_extract(data, '$.c')) as \"cpu\"\nFROM telemetry\nWHERE event_date BETWEEN ${__from:date:seconds} AND ${__to:date:seconds}\nGROUP BY 1\nORDER BY 1 ASC",
     "timeColumns": [ "event_date" ]
    }
   ]
  },
  {
   "title": "GPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "queryText": "SELECT \n\t$__unixEpochGroupSeconds(event_date, 60, NULL) as event_date, \n\tAVG(CAST(IFNULL(json_extract(data, '$.g_3d'), 0.0) AS FLOAT)) as \"3d\"\nFROM telemetry\nWHERE event_date BETWEEN ${__from:date:seconds} AND ${__to:date:seconds}\nGROUP BY 1\nORDER BY 1 ASC",
     "rawQueryText": "SELECT \n\t$__unixEpochGroupSeconds(event_date, 60, NULL) as event_date, \n\tAVG(CAST(IFNULL(json_extract(data, '$.g_3d'), 0.0) AS FLOAT)) as \"3d\"\nFROM telemetry\nWHERE event_date BETWEEN ${__from:date:seconds} AND ${__to:date:seconds}\nGROUP BY 1\nORDER BY 1 ASC",
     "timeColumns": [ "event_date" ]
    },
    {
     "queryText": "SELECT \n\t$__unixEpochGroupSeconds(event_date, 60, NULL) AS event_date, \n\tAVG(CAST(IFNULL(json_extract(data, '$.g_videodecode'), 0.0) AS FLOAT)) AS \"vdec\"\nFROM telemetry\nWHERE event_date BETWEEN ${__from:date:seconds} AND ${__to:date:seconds}\nGROUP BY 1\nORDER BY 1 ASC",
     "rawQueryText": "SELECT \n\t$__unixEpochGroupSeconds(event_date, 60, NULL) AS event_date, \n\tAVG(CAST(IFNULL(json_extract(data, '$.g_videodecode'), 0.0) AS FLOAT)) AS \"vdec\"\nFROM telemetry\nWHERE event_date BETWEEN ${__from:date:seconds} AND ${__to:date:seconds}\nGROUP BY 1\nORDER BY 1 ASC",
     "timeColumns": [ "event_date" ]
    },
    {
     "queryText": "SELECT \n\t$__unixEpochGroupSeconds(event_date, 60, NULL) AS event_date, \n\tAVG(CAST(IFNULL(json_extract(data, '$.g_videoprocessing'), 0.0) AS FLOAT)) AS \"vp\"\nFROM telemetry\nWHERE event_date BETWEEN ${__from:date:seconds} AND ${__to:date:seconds}\nGROUP BY 1\nORDER BY 1 ASC",
     "rawQueryText": "SELECT \n\t$__unixEpochGroupSeconds(event_date, 60, NULL) AS event_date, \n\tAVG(CAST(IFNULL(json_extract(data, '$.g_videoprocessing'), 0.0) AS FLOAT)) AS \"vp\"\nFROM telemetry\nWHERE event_date BETWEEN ${__from:date:seconds} AND ${__to:date:seconds}\nGROUP BY 1\nORDER BY 1 ASC",
     "timeColumns": [ "event_date" ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "queryText": "SELECT $__unixEpochGroupSeconds(event_date, 60, NULL) as event_date, avg(json_extract(data, '$.am')) as 'Free RAM'\nFROM telemetry\nWHERE event_date BETWEEN ${__from:date:seconds} AND ${__to:date:seconds}\nGROUP BY 1\nORDER BY 1 ASC",
     "rawQueryText": "SELECT $__unixEpochGroupSeconds(event_date, 60, NULL) as event_date, avg(json_extract(data, '$.am')) as 'Free RAM'\nFROM telemetry\nWHERE event_date BETWEEN ${__from:date:seconds} AND ${__to:date:seconds}\nGROUP BY 1\nORDER BY 1 ASC",
     "timeColumns": [ "event_date" ]
    },
    {
     "queryText": "SELECT $__unixEpochGroupSeconds(event_date, 60, NULL) as event_date, avg(json_extract(data, '$.pfs')) as 'Page Faults'\nFROM telemetry\nWHERE event_date BETWEEN ${__from:date:seconds} AND ${__to:date:seconds}\nGROUP BY 1\nORDER BY 1 ASC",
     "rawQueryText": "SELECT $__unixEpochGroupSeconds(event_date, 60, NULL) as event_date, avg(json_extract(data, '$.pfs')) as 'Page Faults'\nFROM telemetry\nWHERE event_date BETWEEN ${__from:date:seconds} AND ${__to:date:seconds}\nGROUP BY 1\nORDER BY 1 ASC",
     "timeColumns": [ "event_date" ]
    }
   ]
  },
  {
   "title": "Disk IO (Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "queryText": "SELECT \n\t$__unixEpochGroupSeconds(event_date, 60, NULL) as event_date, \n\tavg(json_extract(data, '$.dr')) as \"Disk Read\"\nFROM telemetry\nWHERE event_date BETWEEN ${__from:date:seconds} AND ${__to:date:seconds}\nGROUP BY 1\nORDER BY 1 ASC",
     "rawQueryText": "SELECT \n\t$__unixEpochGroupSeconds(event_date, 60, NULL) as event_date, \n\tavg(json_extract(data, '$.dr')) as \"Disk Read\"\nFROM telemetry\nWHERE event_date BETWEEN ${__from:date:seconds} AND ${__to:date:seconds}\nGROUP BY 1\nORDER BY 1 ASC",
     "timeColumns": [ "event_date" ]
    },
    {
     "queryText": "SELECT \n\t$__unixEpochGroupSeconds(event_date, 60, NULL) as event_date, \n\tavg(json_extract(data, '$.dw')) as \"Disk Write\"\nFROM telemetry\nWHERE event_date BETWEEN ${__from:date:seconds} AND ${__to:date:seconds}\nGROUP BY 1\nORDER BY 1 ASC",
     "rawQueryText": "SELECT \n\t$__unixEpochGroupSeconds(event_date, 60, NULL) as event_date, \n\tavg(json_extract(data, '$.dw')) as \"Disk Write\"\nFROM telemetry\nWHERE event_date BETWEEN ${__from:date:seconds} AND ${__to:date:seconds}\nGROUP BY 1\nORDER BY 1 ASC",
     "timeColumns": [ "event_date" ]
    }
   ]
  },
  {
   "title": "Network IO (Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "queryText": "SELECT \n\t$__unixEpochGroupSeconds(event_date, 60, NULL) as event_date, \n\tavg(json_extract(data, '$.ni')) as \"Net In\"\nFROM telemetry\nWHERE event_date BETWEEN ${__from:date:seconds} AND ${__to:date:seconds}\nGROUP BY 1\nORDER BY 1 ASC",
     "rawQueryText": "SELECT \n\t$__unixEpochGroupSeconds(event_date, 60, NULL) as event_date, \n\tavg(json_extract(data, '$.ni')) as \"Net In\"\nFROM telemetry\nWHERE event_date BETWEEN ${__from:date:seconds} AND ${__to:date:seconds}\nGROUP BY 1\nORDER BY 1 ASC",
     "timeColumns": [ "event_date" ]
    },
    {
     "queryText": "SELECT \n\t$__unixEpochGroupSeconds(event_date, 60, NULL) as event_date, \n\tavg(json_extract(data, '$.no')) as \"Net Out\"\nFROM telemetry\nWHERE event_date BETWEEN ${__from:date:seconds} AND ${__to:date:seconds}\nGROUP BY 1\nORDER BY 1 ASC",
     "rawQueryText": "SELECT \n\t$__unixEpochGroupSeconds(event_date, 60, NULL) as event_date, \n\tavg(json_extract(data, '$.no')) as \"Net Out\"\nFROM telemetry\nWHERE event_date BETWEEN ${__from:date:seconds} AND ${__to:date:seconds}\nGROUP BY 1\nORDER BY 1 ASC",
     "timeColumns": [ "event_date" ]
    }
   ]
  }
 ]
}