{
 "title": "Media Vault System Info",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Emby Playback Sessions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  event_date AS \"time\",\n  (data->'p')::float AS \"Playing\"\nFROM events\nWHERE\n  $__timeFilter(event_date) AND\n  data_type = 'emby'\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  event_date AS \"time\",\n  (data->'vt')::float AS \"VideoTranscode\"\nFROM events\nWHERE\n  $__timeFilter(event_date) AND\n  data_type = 'emby'\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  event_date AS \"time\",\n  (data->'at')::float AS \"AudioTranscode\"\nFROM events\nWHERE\n  $__timeFilter(event_date) AND\n  data_type = 'emby'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Emby Device Sessions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  event_date AS \"time\",\n  (data->'a')::float AS \"Active\"\nFROM events\nWHERE\n  $__timeFilter(event_date) AND\n  data_type = 'emby'\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  event_date AS \"time\",\n  (data->'t')::float AS \"Total\"\nFROM events\nWHERE\n  $__timeFilter(event_date) AND\n  data_type = 'emby'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "CPU (%)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  event_date AS \"time\",\n  (data->'c')::float AS \"cpu\"\nFROM events\nWHERE\n  $__timeFilter(event_date) AND\n  data_type = 'server'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Disk IO (Bytes/s)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  event_date AS \"time\",\n  (data->'dr')::float AS \"Disk Read\"\nFROM events\nWHERE\n  $__timeFilter(event_date) AND\n  data_type = 'server'\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  event_date AS \"time\",\n  (data->'dw')::float AS \"Disk Write\"\nFROM events\nWHERE\n  $__timeFilter(event_date) AND\n  data_type = 'server'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Memory (%)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  event_date AS \"time\",\n  (data->'am')::float AS \"mem\"\nFROM events\nWHERE\n  $__timeFilter(event_date) AND\n  data_type = 'server'\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  event_date AS \"time\",\n  (data->'pfs')::float AS \"pfs\"\nFROM events\nWHERE\n  $__timeFilter(event_date) AND\n  data_type = 'server'\nORDER BY 1\n"
    }
   ]
  },
  {
   "title": "Network IO (Bits/s)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  event_date AS \"time\",\n  (data->'ni')::float AS \"Net In\"\nFROM events\nWHERE\n  $__timeFilter(event_date) AND\n  data_type = 'server'\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  event_date AS \"time\",\n  (data->'no')::float AS \"Net Out\"\nFROM events\nWHERE\n  $__timeFilter(event_date) AND\n  data_type = 'server'\nORDER BY 1"
    }
   ]
  }
 ]
}