{
 "title": "Temperature",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  event_date AS \"time\",\n  (data->'t')::float AS \"Temp\"\nFROM environment\nORDER BY event_date desc\nlimit 1"
    }
   ]
  },
  {
   "title": "Relative Humidity",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  event_date AS \"time\",\n  (data->'rh')::float AS \"RH\"\nFROM environment\nORDER BY event_date desc\nlimit 1"
    }
   ]
  },
  {
   "title": "Barometric Pressure",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  event_date AS \"time\",\n  (data->'hpa')::float AS \"hPa\"\nFROM environment\nORDER BY event_date desc\nlimit 1\n"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  event_date AS \"time\",\n  (data->'t')::float AS \"`C\"\nFROM environment\nWHERE\n  $__timeFilter(event_date) AND\n  data_type = 's1'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Barometric Pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT\n  event_date AS \"time\",\n  (data->'hpa')::float AS \"hPa\"\nFROM environment\nWHERE\n  $__timeFilter(event_date) AND\n  data_type = 's1'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Relative Humidity",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  event_date AS \"time\",\n  (data->'rh')::float AS \"rh\"\nFROM environment\nWHERE\n  $__timeFilter(event_date) AND\n  data_type = 's1'\nORDER BY 1"
    }
   ]
  }
 ]
}